AWSTemplateFormatVersion: 2010-09-09
Description: IAM user and policy for sampleapi CI/CD pipeline
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
        - Label:
            default: IAM policy and user parameters
          Parameters:
            - S3BucketPrefix
            - OrganizationDomain
            - ClusterName
            - ServiceName
            - AppName
            - ECSTaskExecutionRoleName
            - ResourceOwner

    ParameterLabels:
      S3BucketPrefix:
        default: Prefix of S3 bucket
      OrganizationDomain:
        default: Domain name of your organization
      ClusterName:
        default: Name of ECS cluster
      ServiceName:
        default: Name of service in ECS cluster
      AppName:
        default: Name of application running in container
      ECSTaskExecutionRoleName:
        default: Name of ECS task execution role
      ResourceOwner:
        default: Name of owner

Parameters:
  S3BucketPrefix:
      Type: String
      Default: my-bucket
      MinLength: 1
      MaxLength: 32
      Description: Bucket prefix (s3://prefix.my-domain.com)

  OrganizationDomain:
      Type: String
      Default: my-domain.com
      MinLength: 1
      MaxLength: 32
      Description: DNS domain of your organization (e.g. my-domain.com)

  ClusterName:
    Type: String
    Default: sampleapi-ecs-cluster
    MinLength: 1
    MaxLength: 32
    Description: Name of ECS cluster to which the code will be deployed

  ServiceName:
    Type: String
    Default: sampleapi-ecs-service
    MinLength: 1
    MaxLength: 32
    Description: Name of ECS service in cluster to manage tasks

  AppName:
    Type: String
    Default: sampleapi
    MinLength: 1
    MaxLength: 32
    Description: Name of the application running in container

  ECSTaskExecutionRoleName:
      Type: String
      Default: ecsTaskExecutionRole
      MinLength: 1
      MaxLength: 32
      Description: Short name of ECS task execution role

  ResourceOwner:
    Type: String
    Default: me
    MinLength: 1
    MaxLength: 64
    Description: Owner (stored in tags)

Resources:
  SampleapiCICDUser:
    Type: AWS::IAM::User
    Properties:
      Path: /
      UserName: !Join
        - ''
        - - !Ref AppName
          - CicdUser
      Tags:
        - Key: Name
          Value: !Join
            - ''
            - - !Ref AppName
              - CicdUser
        - Key: Owner
          Value: !Ref ResourceOwner

  SampleapiCICDPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Join
        - ''
        - - !Ref AppName
          - CicdPolicy
      Description: Allows CI/CD pipeline access S3, ECR and ECS resources
      Users:
        - !Ref SampleapiCICDUser
      PolicyDocument: 
        Version: 2012-10-17
        Statement:
          - Sid: ListObjectsInBucket
            Effect: Allow
            Action:
              - s3:ListBucket
            Resource:
              - !Join
                - ''
                - - "arn:aws:s3:::"
                  - !Ref S3BucketPrefix
                  - "."
                  - !Ref OrganizationDomain
          - Sid: PutObjectsIntoBucket
            Effect: Allow
            Action:
              - s3:PutObject
            Resource:
              - !Join
                - ''
                - - "arn:aws:s3:::"
                  - !Ref S3BucketPrefix
                  - "."
                  - !Ref OrganizationDomain
                  - "/*"
          - Sid: GetAuthorizationToken
            Effect: Allow
            Action:
              - ecr:GetAuthorizationToken
            Resource: "*"
          - Sid: ManageRepositoryContents
            Effect: Allow
            Action:
              - ecr:BatchCheckLayerAvailability
              - ecr:GetDownloadUrlForLayer
              - ecr:GetRepositoryPolicy
              - ecr:DescribeRepositories
              - ecr:ListImages
              - ecr:DescribeImages
              - ecr:BatchGetImage
              - ecr:InitiateLayerUpload
              - ecr:UploadLayerPart
              - ecr:CompleteLayerUpload
              - ecr:PutImage
            Resource:
              - !Join
                - ''
                - - "arn:aws:ecr:"
                  - !Ref AWS::Region
                  - ":"
                  - !Ref AWS::AccountId
                  - ":repository/"
                  - !Ref OrganizationDomain
                  - "/"
                  - !Ref AppName
          - Sid: AccessTaskDefinitions
            Effect: Allow
            Action:
              - ecs:ListClusters
              - ecs:ListServices
              - ecs:ListTaskDefinitions
              - ecs:ListTaskDefinitionFamilies
              - ecs:DescribeTaskDefinition
              - ecs:RegisterTaskDefinition
              - ecs:DeregisterTaskDefinition
            Resource: "*"
          - Sid: PassRolesInTaskDefinition
            Effect: Allow
            Action:
              - iam:PassRole
            Resource:
              - !Join
                - ''
                - - "arn:aws:iam::"
                  - !Ref AWS::AccountId
                  - ":role/"
                  - !Ref ECSTaskExecutionRoleName
          - Sid: DeployService
            Effect: Allow
            Action:
              - ecs:UpdateService
              - ecs:DescribeServices
            Resource:
              - !Join
                - ''
                - - "arn:aws:ecs:"
                  - !Ref AWS::Region
                  - ":"
                  - !Ref AWS::AccountId
                  - ":service/"
                  - !Ref ClusterName
                  - "/"
                  - !Ref ServiceName
          - Sid: ValidateCloudFormationTemplates
            Effect: Allow
            Action:
              - cloudformation:ValidateTemplate
            Resource: "*"