AWSTemplateFormatVersion: 2010-09-09

Description: S3 bucket for storing build artifacts

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
        - Label:
            default: Artifact S3 bucket parameters
          Parameters:
            - BucketName
            - ClusterOwner

    ParameterLabels:
      BucketName:
        default: Name of S3 bucket
      ClusterOwner:
        default: Name of cluster owner

Parameters: 
  BucketName:
    Type: String
    Default: my-bucket.my-domain.com
    MinLength: 1
    MaxLength: 64
    Description: DNS compatibile name of S3 bucket

  ClusterOwner:
    Type: String
    Default: me
    MinLength: 1
    MaxLength: 64
    Description: Owner (stored in tags)

Resources:
  s3Bucket:
    Type: AWS::S3::Bucket
    Properties: 
      AccessControl: Private
      BucketName: !Ref BucketName
      VersioningConfiguration: 
        Status: Suspended
      Tags:
        - Key: Name
          Value: !Ref BucketName
        - Key: Owner
          Value: !Ref ClusterOwner
        - Key: Stack
          Value: !Ref AWS::StackName